drupalwxt/helm-drupal

drupal/templates/job/post-install-site-install.yaml
I ran into an issue when setting up an `external` database as part of this Helm chart. Even though I had disabled the MySQL pod from being created, the `post-install` script would error out since Drush was trying to install against it.
Adding this conditional fixed the issue for me.
=> Added MySQL conditional for post-install script

drupal/templates/cronjob/drupal.yaml, drupal/templates/job/post-install-site-install.yaml
Hi again! I noticed this morning that our cronjobs were never executing due to the missing `EXTERNAL_PASSWORD` coming from the deployment files. I've added that in this PR.
Also fixed the if/else statements so they make sense 👍
=> Added proper if/else flow and added cronjob fix

drupal/conf/nginx.conf, drupal/values.yaml
There is a file upload size limitation of `20m` when using the current Nginx config values. This is a decent size for most deployments however we are running into issues when trying to upload any file larger than this into Drupal, receiving an Nginx error message of `413 Request Entity Too Large`.
The addition of a few lines will make the `client_max_body_size` Nginx value configurable for deployments that require larger file uploads.
=> Configurable nginx value

drupal/conf/settings.d8.php, drupal/conf/settings.d9.php
Ran into a corner case for one of our Drupal instances that requires a TLS connection to its cloud-managed database. Drupal requires a couple extra database PDO configs to achieve this so I figured we could add this as part of the Helm template to make it configurable and future-proof. The added templating within the `settings.php` file allows a developer to add something like this to their `values.yaml` file:
```
external:
enabled: true
driver: mysql
port: 3306
host: myhost.com
database: db_name
user: db_user
password: db_pass
pdo:
- PDO::MYSQL_ATTR_SSL_CA: '/my/cert/location.pem'
- PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT: false
```
=> Added PDO support for external DBs

CHANGELOG.md, docs/architecture.md, docs/kind.yaml, drupal/conf/settings.d8.php, drupal/conf/settings.d9.php, drupal/templates/cronjob/drupal-backup.yaml, drupal/templates/cronjob/drupal.yaml, drupal/templates/deploy/drupal.yaml, drupal/templates/job/post-install-site-install.yaml, drupal/templates/job/post-upgrade-reconfigure.yaml, drupal/values-hostpath-kind.yaml, drupal/values-hostpath-microk8s.yaml, drupal/values-nfs-azurefile.yaml, drupal/values.yaml, test/config.yaml
Move both the private drupal files and configuration sync into the "/private" mount which will link to Azure Files.
The only question I have is knowing the PVC will mount to /private can I for the config-sync directory with emptydir set to /private/config/sync ?
This was done as a request so that can follow Drupal best practice of placement of configuration files.
https://www.drupal.org/docs/configuration-management/changing-the-storage-location-of-the-sync-directory
=> feat(config): Move config to /private mount

drupal/templates/ing/drupal.yaml
Kubernetes Ingress is now out of beta with the updated `networking.k8s.io/v1` apiVersion requiring some changes to the Ingress YAML. Tested this updated Ingress with our `v1.19.3` AKS cluster and works well.
=> Upgraded Ingress apiVersion to networking.k8s.io/v1

drupal/templates/job/post-install-site-install.yaml
Hey again! Was attempting to deploy a new instance of Drupal with the latest Helm chart but kept running into this error, even though I had the `drupal.install` value set to `false`:
`Error: YAML parse error on drupal/templates/job/post-install-site-install.yaml: error converting YAML to JSON: yaml: line 72: did not find expected '-' indicator`
Had to do a lot of debugging through this file but turns out the `{{- end }}` statement for `{{- if .Values.drupal.install }}` was just in the wrong spot. Helm deployment worked after I moved it to the end of the file.
=> Fixed invalid if/end block

drupal/templates/job/post-upgrade-reconfigure.yaml
Hey, hit the same problem as @markwooff but for upgrades.  If `reconfigure: false` the template fails to parse on a `helm upgrade`.
Related to #50
=> Fix: invalid if/end if reconfigure is false

drupal/templates/deploy/drupal.yaml, drupal/values.yaml
Adds an optional block for `resources` and `podAnnotations` to the Drupal deployment.  
Fixes #58
=> Feat(helm): add resources/podAnnotations to Drupal

drupal/templates/deploy/nginx.yaml, drupal7/templates/deploy/nginx.yaml
Simple fix to use the chart's `nginx.imagePullPolicy` value, based on some less simple debugging in our dev cluster where we're using a `latest` tag 😅
=> fix: set nginx imagePullPolicy from values

drupal/values.yaml
This change will fix the issue of media manager in drupal fails to load.
=> Change x-frame-options language path to match site

drupal7/Chart.yaml, drupal7/values.yaml
I believe this is the cause of some warnings in `helm` when configuring additional crons.
=> fix(drupal7): Correct default value type of the additionalCrons object

drupal/templates/cronjob/cron.yaml
This fixes additionalCrons trying to include values from drupal7 namespace.
=> fix - additionalCrons in d8/9

drupal/Chart.yaml, drupal/values.yaml
This replicates a fix made by @zachomedia in drupal7 - #86 - for drupal 8/9
=> fix default value type for additionalCrons

drupal/Chart.yaml, drupal/conf/nginx.conf, drupal/values.yaml, drupal7/Chart.yaml, drupal7/conf/nginx.conf, drupal7/values.yaml
I have a use case for needing a second location entry point from nginx into Drupal. I believe this could be accomplished transparently by making the nginx configuration configurable in a similar way to the Varnish config.
I think the following change is a reasonable and transparent way of adding that support, but I'd appreciate if someone could review the sanity of this approach :)
=> feat(nginx): allow custom nginx locations to be configured in the values

drupal/Chart.yaml, drupal/conf/settings.d8.php, drupal/conf/settings.d9.php, drupal/values.yaml, drupal7/Chart.yaml, drupal7/values.yaml
I'm hoping to add a new value to the external DB config to enable more customization using the Drupal `init_commands` DB settings field. This will allow a developer to modify DB variables on startup such as `sql_mode` or the `isolation` level using the format in the example below:
```
external:
initCommands:
- isolation: "SET SESSION tx_isolation='READ-COMMITTED'"
```
These Helm values will then be applied to the `$databases` Drupal array as follows:
```
$databases['default']['default'] = [
'init_commands' => [
'isolation' => "SET SESSION tx_isolation='READ-COMMITTED'",
],
];
```
=> Update Drupal confs to support DB init_commands

drupal/Chart.yaml, drupal/templates/ing/drupal.yaml, drupal/values.yaml, drupal7/Chart.yaml, drupal7/templates/ing/drupal.yaml, drupal7/values.yaml, solr/Chart.yaml, solr/templates/ing/solr.yaml, solr/values.yaml
The latest Kubernetes versions are removing the deprecated `kubernetes.io/ingress.class` annotation for selecting an Nginx ingress controller and are pushing to use the `.spec.ingressClassName` field (see: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/#what-to-do). Adding this into the Ingress configs will allow a developer to set their Ingress class using the format below:
```
ingress:
enabled: true
className: my-nginx-class
```
=> Update ingress configs with ingressClassName

drupal/Chart.yaml, drupal/templates/deploy/drupal.yaml, drupal/templates/job/post-install-site-install.yaml, drupal/templates/job/post-upgrade-reconfigure.yaml, drupal/values.yaml, drupal7/Chart.yaml, drupal7/templates/deploy/drupal.yaml, drupal7/templates/job/post-install-site-install.yaml, drupal7/templates/job/post-upgrade-reconfigure.yaml, drupal7/values.yaml
Last pull request, I swear! Not a major one but this modification will allow a developer to disable the `init-media-icons-folder` initContainer if it's no longer required (such as when using a persistent volume and the folder already exists). The boolean defaults to `true` but gives one the ability to turn it off as necessary.
=> Optional init for media icons folder

drupal/Chart.yaml, drupal/templates/cronjob/cron.yaml, drupal/templates/cronjob/drupal-backup.yaml, drupal/templates/cronjob/drupal.yaml, drupal7/Chart.yaml, drupal7/templates/cronjob/cron.yaml, drupal7/templates/cronjob/drupal-backup.yaml, drupal7/templates/cronjob/drupal.yaml
CronJobs built into this chart are still using the `batch/v1beta1` apiVersion when they have been out of beta since Kubernetes v1.21 (see https://kubernetes.io/blog/2021/04/08/kubernetes-1-21-release-announcement/#cronjobs-graduate-to-stable).
Added a `semVer` check for clusters meeting the `1.21` requirements to use `batch/v1` with the fallback still in place.
=> Update CronJob apiVersion

drupal/Chart.yaml, drupal/templates/pdb/poddisruptionbudget.yaml, drupal/values.yaml, drupal7/Chart.yaml, drupal7/templates/pdb/poddisruptionbudget.yaml, drupal7/values.yaml
One last handy feature I was hoping to add to the `helm-drupal` chart was the use of `PodDisruptionBudget`s if a developer wanted to ensure a certain amount of pods remain available during any k8s upgrades or node updates.
Added in the Helm values as commented-out fields.
=> Add PodDisruptionBudget to charts

drupal/Chart.yaml, drupal/templates/job/post-upgrade-reconfigure.yaml, drupal/values.yaml, drupal7/Chart.yaml, drupal7/templates/job/post-upgrade-reconfigure.yaml, drupal7/values.yaml
In some cases, running drush updb before a DB migration is causing issues. Making this optional and handling the updb as part of the extra upgrade script is a better option.
=> Make drush updb optional before DB Migration

drupal/Chart.yaml, drupal/conf/nginx.conf, drupal/values.yaml, drupal7/Chart.yaml, drupal7/conf/nginx.conf, drupal7/values.yaml
Ran into a use case where gzip compression needed to be disabled which currently can't be configured. This change should allow developers to disable it if necessary while having it be on by default.
=> Add option to disable gzip compression

charts/drupal/conf/settings.d10.php
Update the settings.php file that comes with 10.3.9 and add the missing state cache flag to remove warning in Drupal status report.
Leave all active setting configurations as-is.
=> Update settings.d10.php to 10.3.9 and add state cache flag
